server:
  port: 8468
logging:
  file: /java/C2S_LOGS/master-ui-api/masterUiApi.log
info:
  component: MASTER UI API
ribbon:
  ReadTimeout: 50000
hystrix.command.default.execution.timeout.enabled: false
security:
  oauth2:
    client:
      client-id:  master-ui-api
c2s:
    client:
      c2s-ui:
        client-id: c2s-ui
        secret: changeit
        client-secret: changeit
        home-url: http://localhost/c2s-ui/home
      provider-ui:
        client-id: provider-ui
        secret: changeit
        client-secret: changeit
        home-url: http://localhost/provider-ui/home
      staff-ui:
        client-id: staff-ui
        secret: changeit
        client-secret: changeit
        home-url: http://localhost/staff-ui/home
      master-ui:
        login-url: http://localhost/master-ui/login
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /master-ui-api